sudo: required
services:
  - docker

before_install:
  - docker build -t dockeryoutube -f Dockerfile.dev .

script:
  - docker run -e CI=true dockeryoutube npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "us-east-2"
  app: "reactapptest"
  env: "Reactapptest-env"
  bucket_name: "eelasticbeanstalk-us-east-2-160885238704"
  bucket_path: "docker-youtube"
  on:
    branch: master

